### ISSUE TITLE
More flexibility with setting the release version for `./script/dock pkg`

### ISSUE THREAD

**Issue by o-fedorov** [percona/orchestrator#36]
I would like to be able to build the latest release of Orchestrator using its [./script/dock](../blob/master/script/dock) and [./build.sh](../blob/master/build.sh) scripts.  There are a couple of issues related to it:

1. The script [./script/dock](../blob/master/script/dock) takes the release version [./RELEASE_VERSION](../blob/master/RELEASE_VERSION) file.  It was set to `3.2.6` 3 years ago, and have not changed since then.
2. Even if I override the contents of [./RELEASE_VERSION](../blob/master/RELEASE_VERSION) with the currently tagged version (`3.2.6-12`), [./build.sh](../blob/master/build.sh) will fail because for `rpm` packages it converts `-` to `_`, and later tries to find the original version string with a dash.
3. Adding version metadata (with `+`) does not work either, since `RELEASE_VERSION` is used to substitute a string used by `sed`, and `+` has a special meaning there.

The following PR fixes the issues: https://github.com/percona/orchestrator/pull/35

1. Pass `RELEASE_VERSION` and `RELEASE_SUBVERSION` environment variables as build arguments to [docker/Dockerfile.packaging](../blob/master/docker/Dockerfile.packaging), and let [./build.sh](../blob/master/build.sh) pick these values.
2. Use only the version core (the `3.2.6` part of a version like `3.2.6-12+...`) for `sed` when renaming the packages.

**Comment by o-fedorov** [comment]
@egegunes, @fabio-silva, @kamil-holubicki, @igroene, could you kindly provide any feedback?

**Comment by kamil-holubicki** [comment]
Hi, I made a couple of comments to the PR 2 weeks ago.
In general looks fine, probably we can approve it. Percona uses its scripts for packaging, so I assume you wanted to create a package yourself? Could you elaborate on this?

**Comment by o-fedorov** [comment]
That is odd, I do not see any comments at all:

<img width="936" alt="Screenshot 2024-05-03 at 09 58 54" src="https://github.com/percona/orchestrator/assets/2283679/13c0e06f-11b2-4cf5-a6db-bdb9cdae50ac">

**Comment by o-fedorov** [comment]
Yes, I see that there were some changes comparing to `openpark/orchestrator`, so my team and I wanted to have them deployed to our infra as well.

We use `deb` packages, so utilizing `./script/dock pkg` is the simplest way to build ones. We use git tags to determine the package version, and right now it requires some complex workaround to make `./script/dock pkg` work as expected.

**Comment by o-fedorov** [comment]
@kamil-holubicki could you please share the links to your comments to the PR, or check if they are submitted, and that there is no access rights limitation? It seems that your comments to the PR are invisible for me at the moment.

**Comment by kamil-holubicki** [comment]
OK, I forgot to submit the review :P .
BTW, you can find Orchestrator on the Percona download page:
https://www.percona.com/downloads
Then select Percona Distribution for MySql and among the packages you will find the Orchestrator

**Comment by o-fedorov** [comment]
We plan to also debug and possibly fix some issues Orchestrator, so we will need dev builds for our process. But thank you for the link, will check how to include Percona builds to our process
